### ISSUE TITLE
Dividing Integer and Float results in unexpected error

### ISSUE THREAD

**Issue by mateidanut** [yurtsiv/mooncake#9]
```
let f = 41
let h = 2.5
f / h

output: src/Interpreter/Eval.hs:(15,1)-(92,33): Non-exhaustive patterns in function evaluate

expected output: user error ("Can divide only integers")
```
This may mean the Parser part does not expect this construct.

**Comment by yurtsiv** [comment]
Thank you for filling out the issue @mateidanut.

I was in the middle of adding floats and implemented only the parser side.
The error you see comes from the interpreter which doesn't handle floats yet.
There're two failing tests currently which may confuse people, so we should either remove them or actually implement floats.

Let me know if you're willing to work on either of that, otherwise, I'll do it :)

**Comment by mateidanut** [comment]
Hey @yurtsiv thanks for the reply!
I noticed that the test suite didn't pass because of the 2 float tests so I removed them in PR #8.
Let me know what do you think when you get to have a look.

Cheers!

**Comment by yurtsiv** [comment]
@mateidanut Aaah, I see. Let's have them commented out for now. Thanks!
